const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {execFile}=require('node:child_process');const {promisify}=require('node:util');const exec=promisify(execFile);const C=require('../src/core.js');const E=require('../electron/exporter.cjs');const ffmpeg=require('ffmpeg-static');
test('Audio and video fades are independent and match overlapping gain ramps',()=>{const c={...C.createClip({id:'a',type:'audio',duration:4}),volume:.8,fadeIn:3,audioFadeIn:1,audioFadeOut:1};assert.equal(C.audioGain(c,0),0);assert.equal(C.audioGain(c,.5),.4);assert.equal(C.audioGain(c,2),.8);assert.equal(C.audioGain(c,3.5),.4);assert.equal(C.audioGain(c,4),0);c.audioFadeIn=20;c.audioFadeOut=20;assert.deepEqual(C.fadeDurations(c),{in:4,out:4});assert.equal(C.audioGain(c,2),.2);c.audioMuted=true;assert.equal(C.audioGain(c,2),0);});
test('Older projects keep their original shared fades during migration',()=>{const p=C.newProject();p.assets=[{id:'v',path:'video.mp4'}];p.clips=[{id:'c',assetId:'v',track:'video',start:0,in:0,out:6,speed:1,volume:1,fadeIn:2,fadeOut:1}];const migrated=C.normalizeProject(p);assert.equal(migrated.clips[0].audioFadeIn,2);assert.equal(migrated.clips[0].audioFadeOut,1);assert.equal(migrated.clips[0].fadeIn,2);assert.equal(migrated.clips[0].audioMuted,false);});
test('Audio extraction retains trim, speed, timing, gain and fades and mutes the original',()=>{const p=C.newProject();p.assets=[{id:'v',duration:10,type:'video',hasAudio:true}];const video={...C.createClip(p.assets[0],2),in:1,out:7,speed:2,volume:.7,audioFadeIn:.5,audioFadeOut:.8};p.clips=[video];const audio=C.detachAudio(p,video.id);assert.equal(audio.track,'audio');assert.equal(audio.start,2);assert.equal(audio.in,1);assert.equal(audio.out,7);assert.equal(audio.speed,2);assert.equal(audio.volume,.7);assert.equal(audio.audioFadeOut,.8);assert.equal(audio.fadeIn,0);assert.equal(video.audioMuted,true);assert.notEqual(audio.id,video.id);});
test('Rendered MP4 audio really fades and muted clips export as silence',async()=>{const dir=path.resolve('.test-output/audio');await fs.mkdir(dir,{recursive:true});const source=path.join(dir,'tone.wav');await exec(ffmpeg,['-y','-v','error','-f','lavfi','-i','sine=frequency=440:duration=4',source],{windowsHide:true});const p=C.newProject();p.assets=[{id:'a',path:source,type:'audio',duration:4,hasAudio:true}];p.clips=[{...C.createClip(p.assets[0]),audioFadeIn:1,audioFadeOut:1,fadeIn:3}];const output=path.join(dir,'fades.mp4');await E.runExport(await E.buildExport(p,{height:720,quality:'standard'},dir,output));
async function rms(file,start){const b=(await exec(ffmpeg,['-v','error','-ss',String(start),'-i',file,'-t','0.1','-vn','-ac','1','-ar','48000','-f','f32le','pipe:1'],{windowsHide:true,encoding:'buffer',maxBuffer:1024*1024})).stdout;let sum=0;for(let i=0;i<b.length/4;i++)sum+=b.readFloatLE(i*4)**2;return Math.sqrt(sum/(b.length/4));}
const plateau=await rms(output,2),intro=await rms(output,.1),outro=await rms(output,3.8);assert.ok(plateau>.05);assert.ok(intro/plateau<.25);assert.ok(outro/plateau<.25);
p.clips[0].audioMuted=true;const muted=path.join(dir,'muted.mp4');await E.runExport(await E.buildExport(p,{height:720,quality:'standard'},dir,muted));assert.ok(await rms(muted,2)<.001);
});
