const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {execFile}=require('node:child_process');const {promisify}=require('node:util');const exec=promisify(execFile);const ffmpeg=require('ffmpeg-static');const probe=require('ffprobe-static').path;const C=require('../src/core.js');const E=require('../electron/exporter.cjs');
test('MP4 export renders cuts, gaps, overlapping text, speed, fades, rotation, and mixed audio',async()=>{
const dir=path.resolve('.test-output');await fs.mkdir(dir,{recursive:true});const source=path.join(dir,'source.mp4'),audio=path.join(dir,'music.wav'),output=path.join(dir,'result.mp4');
await exec(ffmpeg,['-y','-v','error','-f','lavfi','-i','testsrc2=size=320x180:rate=30:duration=3','-f','lavfi','-i','sine=frequency=440:duration=3','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest',source],{windowsHide:true});
await exec(ffmpeg,['-y','-v','error','-f','lavfi','-i','sine=frequency=220:duration=4',audio],{windowsHide:true});
const p=C.newProject();p.assets=[{id:'v',path:source,name:'source',type:'video',width:320,height:180,duration:3,hasAudio:true},{id:'a',path:audio,name:'music',type:'audio',duration:4,hasAudio:true}];p.clips=[{...C.createClip(p.assets[0],.4),in:.2,out:2.2,speed:2,rotation:5,fadeIn:.15,fadeOut:.2,brightness:.02,volume:.5},{...C.createClip(p.assets[1],0),out:2,volume:.2},{...C.createText(.25),out:1.5,text:'A cut: 100%\nIt’s your story',fontSize:72}];p.ratio='16:9';const plan=await E.buildExport(p,{height:720,quality:'standard'},dir,output);let last=0;await E.runExport(plan,p=>{last=p;});assert.equal(last,100);const meta=JSON.parse((await exec(probe,['-v','error','-show_format','-show_streams','-of','json',output],{windowsHide:true})).stdout);assert.ok(Math.abs(Number(meta.format.duration)-2)<.12);const v=meta.streams.find(s=>s.codec_type==='video');assert.equal(v.width,1280);assert.equal(v.height,720);assert.ok(meta.streams.some(s=>s.codec_type==='audio'));
});
test('Export cancellation stops rendering without returning success',async()=>{const dir=path.resolve('.test-output');await fs.mkdir(dir,{recursive:true});const p=C.newProject();p.clips=[{...C.createText(0),out:60}];const plan=await E.buildExport(p,{height:1080,quality:'high'},dir,path.join(dir,'cancelled.mp4'));const abort=new AbortController();abort.abort();await assert.rejects(E.runExport(plan,()=>{},abort.signal),/cancelled/);});
test('Speed filters support the whole allowed range',()=>{assert.equal(E.atempo(4),'atempo=2,atempo=2');assert.equal(E.atempo(.25),'atempo=0.5,atempo=0.5');});
