const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../src/core.js');
function fixture(){const p=C.newProject(),a={id:'a',type:'video',path:'a.mp4',duration:2};p.assets=[a];p.clips=[C.createClip(a),C.createClip(a,2),C.createClip(a,4)];return p;}
test('Magnetic rearrangement carries attached titles and extracted audio; linkage can be disabled',()=>{for(const linked of [true,false]){const p=fixture();p.timeline.linkage=linked;const middle=p.clips[1],title=C.createText(2.5),audio={...C.createClip(p.assets[0],2),track:'audio'};p.clips.push(title,audio);C.reorderMain(p,[middle.id],10);assert.equal(middle.start,4);assert.equal(p.clips[2].start,2);assert.equal(title.start,linked?4.5:2.5);assert.equal(audio.start,linked?4:2);}});
test('Deleting and trimming main clips close the sequence while free mode preserves gaps',()=>{const p=fixture(),last=p.clips[2],anchors=C.captureAnchors(p);p.clips[0].out=1;C.reflowMain(p,C.mainSequence(p),anchors);assert.equal(last.start,3);C.removeTimelineClips(p,[p.clips[1].id]);assert.equal(last.start,1);const free=fixture();free.timeline.magnetic=false;C.removeTimelineClips(free,[free.clips[1].id]);assert.equal(free.clips[1].start,4);});
test('Snapping chooses the closest start or end edge and ignores the moving selection',()=>{const p=fixture();const result=C.snapPlacement(p,1.08,.9,[p.clips[0].id],10,.15,true);assert.equal(result.start,1.1);assert.equal(result.guide,2);const free=C.snapPlacement(p,1.081,.9,[],10,.15,false);assert.equal(free.start,32/30);assert.equal(free.guide,null);});
test('Persistent lanes survive save/open and legacy overlaps migrate without changing time',()=>{const p=fixture();p.clips[1].start=1;delete p.clips[0].lane;delete p.clips[1].lane;delete p.clips[2].lane;delete p.timeline;const loaded=C.normalizeProject(p);assert.deepEqual(loaded.clips.map(c=>c.lane),[0,1,0]);assert.deepEqual(loaded.clips.map(c=>c.start),[0,1,4]);assert.equal(loaded.timeline.magnetic,false);loaded.clips[1].start=6;assert.equal(C.normalizeProject(loaded).clips[1].lane,1);});
test('Locked tracks resist removal and rearrangement; visibility and stacking follow lane identity',()=>{const p=fixture();p.trackStates['video:0']={locked:true};assert.equal(C.removeTimelineClips(p,[p.clips[1].id]),false);assert.throws(()=>C.reorderMain(p,[p.clips[1].id],0),/Unlock/);const overlay={...C.createClip(p.assets[0]),lane:2};p.clips.unshift(overlay);assert.equal(C.active(p,1,'video').at(-1).id,overlay.id);p.trackStates['video:2']={hidden:true};assert.ok(!C.active(p,1,'video').includes(overlay));overlay.disabled=true;p.trackStates['video:2'].hidden=false;assert.ok(!C.active(p,1,'video').includes(overlay));});
test('Ripple delete affects only the same persistent lane and respects locked layers',()=>{const p=fixture();p.timeline.magnetic=false;const overlay={...C.createClip(p.assets[0],4),lane:1};p.clips.push(overlay);C.removeTimelineClips(p,[p.clips[1].id],true);assert.equal(p.clips[1].start,2);assert.equal(overlay.start,4);});
test('Export stacks by layer and omits disabled, hidden and muted media consistently',async()=>{const E=require('../electron/exporter.cjs'),p=fixture();p.assets[0]= {...p.assets[0],width:160,height:90,hasAudio:true};const overlay={...C.createClip(p.assets[0]),lane:1};p.assets.push({...p.assets[0],id:'upper',path:'upper.mp4'});overlay.assetId='upper';p.clips=[overlay,p.clips[0]];let plan=await E.buildExport(p,{height:180},'.test-output','.test-output/track-test.mp4');const graph=plan.args[plan.args.indexOf('-filter_complex')+1];assert.ok(graph.indexOf('[0:v]')<graph.indexOf('[1:v]'));assert.equal(plan.args[plan.args.indexOf('-i')+1],'a.mp4');p.trackStates['video:1']={hidden:true,muted:true};plan=await E.buildExport(p,{height:180},'.test-output','.test-output/track-test.mp4');const hiddenGraph=plan.args[plan.args.indexOf('-filter_complex')+1];assert.ok(hiddenGraph.includes('[0:v]'));assert.ok(!hiddenGraph.includes('[1:v]'));assert.ok(!hiddenGraph.includes('[1:a]'));overlay.disabled=true;plan=await E.buildExport(p,{height:180},'.test-output','.test-output/track-test.mp4');assert.equal(plan.args.filter(a=>a==='-i').length,1);});
