const {_electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{execFileSync}=require('node:child_process');
(async()=>{const root=path.resolve(__dirname,'..'),qa=path.join(root,'.qa');await fs.mkdir(qa,{recursive:true});let electron;
 try{
  electron=await _electron.launch({executablePath:process.argv[2]||require('electron'),args:process.argv[2]?[]:[root],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined},timeout:60000});const page=await electron.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#preview-import');
  const source=path.join(root,'.test-output/source.mp4'),output=path.join(qa,'ui-export.gif');
  await electron.evaluate(({dialog},d)=>{globalThis.gifSaveDialogs=[];dialog.showOpenDialog=async()=>({canceled:false,filePaths:[d.source]});dialog.showSaveDialog=async(_w,opts)=>{gifSaveDialogs.push(opts);return {canceled:false,filePath:d.output};};},{source,output});
  await page.click('#import-button');await page.waitForSelector('.media-card');await page.locator('[data-add]').first().click();await page.evaluate(()=>{project.fps=24;renderAll();});
  await page.click('#export-button');assert.equal(await page.locator('#export-fps').inputValue(),'24');assert.equal(await page.locator('#export-loop-field').isVisible(),false);
  await page.selectOption('#export-format','gif');assert.equal(await page.locator('#export-resolution').inputValue(),'480');assert.equal(await page.locator('#export-fps').inputValue(),'15');assert.equal(await page.locator('#export-loop-field').isVisible(),true);await page.selectOption('#export-resolution','360');await page.selectOption('#export-fps','10');await page.selectOption('#export-quality','high');await page.uncheck('#export-loop');
  await page.selectOption('#export-format','mp4');assert.equal(await page.locator('#export-resolution').inputValue(),'1080');assert.equal(await page.locator('#export-fps').inputValue(),'24');await page.selectOption('#export-format','gif');assert.equal(await page.locator('#export-resolution').inputValue(),'360');assert.equal(await page.locator('#export-fps').inputValue(),'10');assert.equal(await page.locator('#export-quality').inputValue(),'high');
  const before=await page.evaluate(()=>({fps:project.fps,history:history.length,dirty}));await page.screenshot({path:path.join(qa,'gif-export-dialog.png')});
  await electron.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1000,700));
  const footerTop=await page.locator('#export-form .dialog-actions').evaluate(el=>el.getBoundingClientRect().top);
  for(const id of ['start-export','export-cancel'])assert.ok(await page.locator('#'+id).evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'export actions must remain visible in a small window');
  await page.locator('.export-settings').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(Math.abs(await page.locator('#export-form .dialog-actions').evaluate(el=>el.getBoundingClientRect().top)-footerTop)<1);await page.screenshot({path:path.join(qa,'gif-export-small.png')});
  await page.click('#start-export');await page.waitForFunction(()=>document.querySelector('#export-message').textContent.startsWith('Saved to '),{},{timeout:60000});assert.equal(await page.locator('#export-progress-label').textContent(),'Your GIF is ready');assert.equal(await page.locator('#export-percent').textContent(),'100%');assert.equal(await page.locator('#show-output').isVisible(),true);assert.deepEqual(await page.evaluate(()=>({fps:project.fps,history:history.length,dirty})),before);
  const dialog=await electron.evaluate(()=>gifSaveDialogs.at(-1));assert.equal(dialog.title,'Export GIF');assert.ok(dialog.defaultPath.endsWith('.gif'));assert.deepEqual(dialog.filters,[{name:'GIF animation',extensions:['gif']}]);
  const info=JSON.parse(execFileSync(require('ffprobe-static').path,['-v','error','-count_frames','-show_streams','-of','json',output],{encoding:'utf8',windowsHide:true}));assert.equal(info.streams.length,1);assert.equal(info.streams[0].codec_name,'gif');assert.equal(info.streams[0].height,360);assert.equal(Number(info.streams[0].nb_read_frames),30);assert.equal((await fs.readFile(output)).includes(Buffer.from('NETSCAPE2.0')),false);
  await page.click('#export-cancel');await page.click('#export-button');assert.equal(await page.locator('#export-format').inputValue(),'gif');assert.equal(await page.locator('#export-fps').inputValue(),'10');
  await page.selectOption('#export-format','mp4');await page.selectOption('#export-fps','30');await electron.evaluate(({dialog},output)=>{dialog.showSaveDialog=async(_w,opts)=>({canceled:false,filePath:output});},path.join(qa,'gif-regression.mp4'));await page.click('#start-export');await page.waitForFunction(()=>document.querySelector('#export-message').textContent.startsWith('Saved to '),{},{timeout:60000});assert.equal(await page.evaluate(()=>project.fps),24);
  const mp4=JSON.parse(execFileSync(require('ffprobe-static').path,['-v','error','-show_streams','-of','json',path.join(qa,'gif-regression.mp4')],{encoding:'utf8',windowsHide:true}));assert.equal(mp4.streams.find(s=>s.codec_type==='video').r_frame_rate,'30/1');assert.ok(mp4.streams.some(s=>s.codec_type==='audio'));
  await assert.rejects(page.evaluate(()=>api.exportVideo(project,{format:'gif',height:2160,fps:60,quality:'standard'})),/Invalid export settings/);assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS: GIF dialog, format-specific settings, native save filter, real GIF animation, once looping, project frame rate preserved, MP4 audio/frame rate regression, and invalid settings rejected.');
 }finally{if(electron)await electron.evaluate(({app})=>app.exit(0)).catch(()=>{});}
})().catch(e=>{console.error(e);process.exitCode=1;});
