const {_electron}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'..');let app;try{app=await _electron.launch({executablePath:process.argv[2]||require('electron'),args:process.argv[2]?[]:[root],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined}});const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#magnetic-toggle');await app.evaluate(({dialog},root)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[root+'/.test-output/editing/red.mp4']});},root);await page.click('#import-button');await page.waitForSelector('.media-card');
await page.evaluate(()=>{const asset=project.assets[0];project=C.newProject();project.name='Timeline workflow';project.assets=[asset];project.clips=['a','b','c'].map((id,i)=>({...C.createClip(asset,i*2),id}));project.clips.push({...C.createClip(asset,1),id:'overlay',lane:1,scale:.3,x:.3,y:-.2},{...C.createText(.5),id:'title',text:'The story moves with the scene',out:1,fontSize:42});clearTimelineSelection();history=[];future=[];time=0;zoom=80;renderAll();});
async function dragClip(id,dx,dy=0,edge){const selector='[data-clip="'+id+'"]'+(edge?' [data-handle="'+edge+'"]':'');const b=await page.locator(selector).boundingBox();const x=b.x+(edge?3:Math.min(35,b.width/2)),y=b.y+20;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y+dy,{steps:8});await page.mouse.up();}
await dragClip('c',-320);assert.deepEqual(await page.evaluate(()=>C.mainSequence(project).map(c=>c.id)),['c','a','b']);assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='title').start),2.5);await page.click('#undo');assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='title').start),.5);await page.click('#redo');
await dragClip('c',-40,0,'right');assert.equal(await page.evaluate(()=>C.clipDuration(project.clips.find(c=>c.id==='c'))),1.5);assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='a').start),1.5);await page.click('#undo');
await dragClip('overlay',0,-67);assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='overlay').lane),2);await page.click('#undo');assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='overlay').lane),1);
await page.click('[data-clip="a"]');await page.keyboard.down('Control');await page.click('[data-clip="b"]');await page.keyboard.up('Control');assert.equal(await page.evaluate(()=>selectedClips().length),2);await page.keyboard.press('Control+g');assert.ok(await page.evaluate(()=>project.clips.find(c=>c.id==='a').groupId===project.clips.find(c=>c.id==='b').groupId));await page.evaluate(()=>{clearTimelineSelection();renderAll();});await page.click('[data-clip="a"]');assert.equal(await page.evaluate(()=>selectedClips().length),2);
await page.uncheck('#magnetic-toggle');await dragClip('a',40);assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='a').start),2.5);assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='b').start),4.5);await page.keyboard.press('Control+c');await page.evaluate(()=>seek(6.5));await page.keyboard.press('Control+v');assert.equal(await page.evaluate(()=>selectedClips().length),2);assert.deepEqual(await page.evaluate(()=>selectedClips().map(c=>c.start)),[6.5,8.5]);assert.ok(await page.evaluate(()=>selectedClips()[0].groupId!==project.clips.find(c=>c.id==='a').groupId));await page.click('#undo');assert.equal(await page.evaluate(()=>project.clips.length),5);
await page.click('[data-track-key="video:0"][data-track-control="locked"]');const lockedBefore=await page.evaluate(()=>JSON.stringify(project.clips));await dragClip('a',80);assert.equal(await page.evaluate(()=>JSON.stringify(project.clips)),lockedBefore);assert.ok(await page.locator('#delete').isDisabled());await page.click('[data-track-key="video:0"][data-track-control="locked"]');
await page.click('[data-clip="overlay"]',{button:'right'});assert.ok(await page.locator('#timeline-menu').isVisible());await page.click('[data-timeline-command="disable"]');assert.equal(await page.evaluate(()=>project.clips.find(c=>c.id==='overlay').disabled),true);await page.click('#undo');
await page.evaluate(()=>{clearTimelineSelection();resizeTimeline(410);renderAll();timelineScroll.scrollLeft=0;timelineScroll.scrollTop=0;});const s=await page.locator('#timeline-surface').boundingBox(),t=await page.locator('[data-track="text"]').boundingBox(),v=await page.locator('[data-track="video"]').boundingBox();await page.mouse.move(s.x+2,t.y+3);await page.mouse.down();await page.mouse.move(s.x+550,v.y+v.height-3,{steps:8});await page.mouse.up();assert.ok(await page.evaluate(()=>selectedClips().length>=4),JSON.stringify(await page.evaluate(()=>({ids:selectedClips().map(c=>c.id),gesture:timelineGesture,scroll:timelineScroll.scrollTop})))+' geometry '+JSON.stringify({s,t,v}));
await page.evaluate(()=>{selectTimelineIds(['overlay']);time=1.5;tab='media';inspectorTab='video';timelineScroll.scrollLeft=0;renderAll();syncMedia();});await page.waitForTimeout(400);await page.evaluate(()=>{draw();document.querySelector('#toast').hidden=true;});await page.screenshot({path:root+'/.qa/timeline-1.4.png'});assert.deepEqual(errors,[]);console.log('PASS: magnetic rearrangement, attached titles, sequence trimming, persistent layer dragging, multi-selection, grouping, clipboard, locks, context menu, marquee selection and undo.');}finally{if(app)await app.evaluate(({app})=>app.exit(0)).catch(()=>{});}})().catch(e=>{console.error(e);process.exitCode=1;});
