(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.EditorCore=factory();})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const clipDuration=c=>(c.out-c.in)/(c.speed||1);
const duration=p=>Math.max(0,...p.clips.map(c=>c.start+clipDuration(c)));
const active=(p,t,track)=>orderedClips(p,track).filter(c=>!c.disabled&&!trackState(p,c).hidden&&t>=c.start&&t<c.start+clipDuration(c));
const animatedKeys=['x','y','opacity','volume'];
const defaults={x:0,y:0,opacity:1,volume:1};
function normalizeKeyframes(frames){if(!Array.isArray(frames))return [];return frames.slice(0,500).map(f=>({time:clamp(f.time,0,86400),values:Object.fromEntries(animatedKeys.filter(k=>Number.isFinite(f.values?.[k])).map(k=>[k,clamp(f.values[k],k==='x'||k==='y'?-1:0,k==='opacity'?1:k==='volume'?2:1)]))})).filter(f=>Object.keys(f.values).length).sort((a,b)=>a.time-b.time).filter((f,i,a)=>i===0||f.time>a[i-1].time+.00001);}
function propertyAt(c,key,local){const base=c[key]??defaults[key]??0,frames=(c.keyframes||[]).filter(f=>Number.isFinite(f.values?.[key]));if(!frames.length)return base;if(local<=frames[0].time)return frames[0].values[key];for(let i=1;i<frames.length;i++){if(local<=frames[i].time){const a=frames[i-1],b=frames[i],u=(local-a.time)/(b.time-a.time);return a.values[key]+(b.values[key]-a.values[key])*u;}}return frames.at(-1).values[key];}
function evaluated(c,local){return {...c,...Object.fromEntries(animatedKeys.map(k=>[k,propertyAt(c,k,local)]))};}
function setKeyframe(c,local,values){local=clamp(local,0,clipDuration(c));const frames=normalizeKeyframes(c.keyframes),existing=frames.find(f=>Math.abs(f.time-local)<.001);if(existing)Object.assign(existing.values,values);else frames.push({time:local,values});c.keyframes=normalizeKeyframes(frames);return c.keyframes;}
function propertyExpression(c,key,variable='t'){const frames=(c.keyframes||[]).filter(f=>Number.isFinite(f.values?.[key]));if(!frames.length)return String(c[key]??defaults[key]??0);let expression=String(frames.at(-1).values[key]);for(let i=frames.length-1;i>0;i--){const a=frames[i-1],b=frames[i],segment='('+a.values[key]+'+('+b.values[key]+'-'+a.values[key]+')*('+variable+'-'+a.time+')/'+(b.time-a.time)+')';expression='if(lt('+variable+','+b.time+'),'+segment+','+expression+')';}return 'if(lte('+variable+','+frames[0].time+'),'+frames[0].values[key]+','+expression+')';}
function reframeKeyframes(c,original){if(!original.keyframes?.length)return;const offset=(c.in-original.in)/(original.speed||1),factor=(c.speed||1)/(original.speed||1),d=clipDuration(c);const frames=original.keyframes.map(f=>({time:(f.time-offset)/factor,values:{...f.values}})).filter(f=>f.time>0&&f.time<d);for(const t of [0,d])frames.push({time:t,values:Object.fromEntries(animatedKeys.filter(k=>original.keyframes.some(f=>k in f.values)).map(k=>[k,propertyAt(original,k,offset+t*factor)]))});c.keyframes=normalizeKeyframes(frames);}
function motionPreset(c,name,duration=.6){const d=clipDuration(c),span=Math.min(duration,d/2),base={x:c.x||0,y:c.y||0,opacity:c.opacity??1};if(name==='none'){c.keyframes=[];return;}const first={...base},last={...base};if(name==='fade')first.opacity=0;if(name==='slide')first.x=clamp(base.x-.3,-1,1);if(name==='rise'){first.y=clamp(base.y+.2,-1,1);first.opacity=0;}c.keyframes=[{time:0,values:first},{time:span,values:base},{time:d-span,values:base},{time:d,values:{...last,opacity:0}}];c.keyframes=normalizeKeyframes(c.keyframes);}
function rippleDelete(p,id){const c=p.clips.find(c=>c.id===id);if(!c)return false;const end=c.start+clipDuration(c),d=clipDuration(c);p.clips=p.clips.filter(x=>x.id!==id);for(const x of p.clips){if(x.track===c.track&&x.start>=end-.00001)x.start=Math.max(0,x.start-d);if(x.transitionIn?.fromId===id)delete x.transitionIn;}return true;}
const fonts={Arial:{regular:'arial.ttf',bold:'arialbd.ttf'},Georgia:{regular:'georgia.ttf',bold:'georgiab.ttf'},'Courier New':{regular:'cour.ttf',bold:'courbd.ttf'}};
function newProject(){return {version:1,name:'Untitled project',ratio:'16:9',fps:30,assets:[],clips:[],timeline:{magnetic:true,linkage:true,snapping:true},trackStates:{}};}
const lane=c=>clamp(c.lane,0,15);
const trackKey=c=>c.track+':'+lane(c);
const trackState=(p,c)=>p.trackStates?.[trackKey(c)]||{};
const isMain=c=>c.track==='video'&&lane(c)===0;
const frameTime=(t,fps=30)=>Math.max(0,Math.round(t*fps)/fps);
const orderedClips=(p,track)=>p.clips.filter(c=>!track||c.track===track).map((c,i)=>({c,i})).sort((a,b)=>lane(a.c)-lane(b.c)||a.i-b.i).map(x=>x.c);
function availableLane(p,c,minimum=0){for(let l=minimum;l<16;l++)if(!trackState(p,{...c,lane:l}).locked&&!p.clips.some(x=>x.id!==c.id&&x.track===c.track&&lane(x)===l&&x.start<c.start+clipDuration(c)-.00001&&x.start+clipDuration(x)>c.start+.00001))return l;throw Error('All sixteen layers are occupied or locked.');}
function arrangeVideo(p,id,time,layout){const c=p.clips.find(c=>c.id===id&&c.track==='video');if(!c)throw Error('Select a video clip first.');if(trackState(p,c).locked)throw Error('Unlock this video layer first.');const set=(clip,scale,x,y)=>{clip.scale=scale;clip.x=x;clip.y=y;const local=clamp(time-clip.start,0,clipDuration(clip));for(const [key,value]of [['x',x],['y',y]])if(clip.keyframes?.some(f=>key in f.values))setKeyframe(clip,local,{[key]:value});};if(layout==='inset'){set(c,.32,.3,.3);return [c];}if(layout==='full'){set(c,1,0,0);return [c];}if(layout!=='side-by-side')throw Error('Unknown video layout.');const visible=active(p,time,'video');if(!visible.includes(c))throw Error('Move the playhead where both videos overlap.');const other=visible.filter(x=>x.id!==id).sort((a,b)=>Math.abs(lane(a)-lane(c))-Math.abs(lane(b)-lane(c))||lane(b)-lane(a))[0];if(!other)throw Error('Place a second video on another layer at this time.');if(trackState(p,other).locked)throw Error('Unlock both video layers first.');const left=lane(c)<lane(other)?c:other,right=left===c?other:c;set(left,.5,-.25,0);set(right,.5,.25,0);return [left,right];}
function assignLegacyLanes(p){for(const c of p.clips){if(Number.isFinite(c.lane))continue;const from=p.clips.find(x=>x.id===c.transitionIn?.fromId);c.lane=from?lane(from):0;const assigned=p.clips.filter(x=>x!==c&&Number.isFinite(x.lane));if(!from)c.lane=availableLane({...p,clips:assigned},c);}}
function mainSequence(p){return p.clips.filter(isMain).sort((a,b)=>a.start-b.start||p.clips.indexOf(a)-p.clips.indexOf(b));}
function captureAnchors(p){const main=mainSequence(p);return p.clips.filter(c=>!isMain(c)).map(c=>{const parent=main.find(x=>x.id===c.anchorId)||main.find(x=>c.start>=x.start-.00001&&c.start<x.start+clipDuration(x));return parent?{id:c.id,parent:parent.id,start:c.start,parentStart:parent.start}:null;}).filter(Boolean);}
function reflowMain(p,order=mainSequence(p),anchors=captureAnchors(p)){let cursor=0,previous=null;for(const c of order){if(c.transitionIn&&c.transitionIn.fromId!==previous?.id)delete c.transitionIn;const overlap=c.transitionIn?Math.min(c.transitionIn.duration,clipDuration(previous)/2,clipDuration(c)/2):0;c.start=Math.max(0,cursor-overlap);cursor=c.start+clipDuration(c);previous=c;}if(p.timeline?.linkage)for(const anchor of anchors){const child=p.clips.find(c=>c.id===anchor.id),parent=order.find(c=>c.id===anchor.parent);if(child&&parent&&!trackState(p,child).locked){child.start=Math.max(0,anchor.start+parent.start-anchor.parentStart);child.anchorId=parent.id;}}return order;}
function insertionIndex(clips,time){const index=clips.findIndex(c=>time<c.start+clipDuration(c)/2);return index<0?clips.length:index;}
function reorderMain(p,ids,time,anchors=captureAnchors(p)){const set=new Set(ids),sequence=mainSequence(p),moving=sequence.filter(c=>set.has(c.id));if(!moving.length)return false;if(sequence.some(c=>trackState(p,c).locked))throw Error('Unlock the main track before rearranging it.');const rest=sequence.filter(c=>!set.has(c.id)),index=insertionIndex(rest,time);rest.splice(index,0,...moving);reflowMain(p,rest,anchors);return true;}
function snapPlacement(p,start,length,ids,playhead,threshold,enabled=true){start=frameTime(start,p.fps);if(!enabled)return {start,guide:null};const exclude=new Set(ids),targets=[0,playhead,...p.clips.filter(c=>!exclude.has(c.id)).flatMap(c=>[c.start,c.start+clipDuration(c)])];let best=null;for(const target of targets)for(const edge of [0,length]){const delta=target-start-edge;if(Math.abs(delta)<=threshold&&(!best||Math.abs(delta)<Math.abs(best.delta)))best={delta,target};}return best&&start+best.delta>=0?{start:Math.max(0,start+best.delta),guide:best.target}:{start,guide:null};}
function removeTimelineClips(p,ids,ripple=false){const set=new Set(ids),removed=p.clips.filter(c=>set.has(c.id)&&!trackState(p,c).locked);if(!removed.length)return false;const anchors=captureAnchors(p);p.clips=p.clips.filter(c=>!removed.includes(c));for(const c of p.clips){if(removed.some(x=>x.id===c.transitionIn?.fromId))delete c.transitionIn;if(removed.some(x=>x.id===c.anchorId))delete c.anchorId;}if(p.timeline?.magnetic&&removed.some(isMain))reflowMain(p,mainSequence(p),anchors);if(ripple)for(const c of p.clips){if(p.timeline?.magnetic&&isMain(c))continue;const before=c.start;const amount=removed.filter(x=>trackKey(x)===trackKey(c)&&x.start+clipDuration(x)<=before+.00001).reduce((sum,x)=>sum+clipDuration(x),0);if(!trackState(p,c).locked)c.start=Math.max(0,c.start-amount);}return removed;}
function createClip(asset,start=0){return {id:uid(),assetId:asset.id,track:asset.type==='audio'?'audio':'video',start,in:0,out:asset.type==='image'?5:asset.duration,speed:1,volume:1,scale:1,x:0,y:0,rotation:0,brightness:0,contrast:1,saturation:1,fadeIn:0,fadeOut:0,audioFadeIn:0,audioFadeOut:0,audioMuted:false,opacity:1,keyframes:[],lane:0};}
function createText(start=0){return {id:uid(),track:'text',start,in:0,out:4,speed:1,text:'Your story starts here',fontSize:64,color:'#ffffff',x:0,y:0.3,bold:true,fontFamily:'Arial',strokeWidth:0,strokeColor:'#000000',background:false,backgroundColor:'#15151b',shadow:true,opacity:1,keyframes:[],lane:0};}
function splitClip(p,id,time){const c=p.clips.find(c=>c.id===id);if(!c||time<=c.start+.05||time>=c.start+clipDuration(c)-.05)return false;const original=JSON.parse(JSON.stringify(c));const cut=c.in+(time-c.start)*(c.speed||1);const right={...c,id:uid(),start:time,in:cut,fadeIn:0,audioFadeIn:0,transitionIn:undefined};c.out=cut;c.fadeOut=0;c.audioFadeOut=0;reframeKeyframes(c,original);reframeKeyframes(right,original);p.clips.splice(p.clips.indexOf(c)+1,0,right);for(const next of p.clips)if(next.transitionIn?.fromId===c.id&&next.start>=time)next.transitionIn={...next.transitionIn,fromId:right.id};return right;}
function fadeDurations(c,kind='audio'){const d=clipDuration(c);return {in:clamp(kind==='audio'?(c.audioFadeIn??c.fadeIn):c.fadeIn,0,d),out:clamp(kind==='audio'?(c.audioFadeOut??c.fadeOut):c.fadeOut,0,d)};}
function fadeGain(c,local,kind='audio'){const d=clipDuration(c);if(local<0||local>d)return 0;const f=fadeDurations(c,kind);return clamp(f.in?local/f.in:1,0,1)*clamp(f.out?(d-local)/f.out:1,0,1);}
function audioGain(c,local){return c.audioMuted?0:clamp(propertyAt(c,'volume',local),0,2)*fadeGain(c,local,'audio');}
function detachAudio(p,id){const c=p.clips.find(c=>c.id===id),a=p.assets.find(a=>a.id===c?.assetId);if(!c||c.track!=='video'||!a?.hasAudio)return null;const audio={...c,id:uid(),track:'audio',fadeIn:0,fadeOut:0,audioFadeIn:c.audioFadeIn??c.fadeIn??0,audioFadeOut:c.audioFadeOut??c.fadeOut??0,audioMuted:false};audio.lane=availableLane(p,audio);audio.groupId=c.groupId||uid();c.groupId=audio.groupId;delete audio.transitionIn;c.audioMuted=true;p.clips.push(audio);return audio;}
function transitionFor(p,c){const t=c.transitionIn;if(!t||!['dissolve','fadeblack'].includes(t.type)||c.track!=='video'||c.disabled||trackState(p,c).hidden)return null;const from=p.clips.find(x=>x.id===t.fromId&&x.track==='video');if(!from||from.disabled||trackState(p,from).hidden||lane(from)!==lane(c)||from.start>c.start)return null;const overlap=from.start+clipDuration(from)-c.start;const d=Math.min(t.duration,overlap,clipDuration(c));return d>.001?{from,duration:d,type:t.type}:null;}
function videoGain(p,c,local){const t=transitionFor(p,c);return propertyAt(c,'opacity',local)*fadeGain(c,local,'video')*(t?clamp(t.type==='fadeblack'?(local/t.duration-.5)*2:local/t.duration,0,1):1)*outgoingTransitionGain(p,c,local);}
function outgoingTransitionGain(p,c,local){const incoming=p.clips.find(x=>x.transitionIn?.fromId===c.id&&x.transitionIn.type==='fadeblack');const t=incoming&&transitionFor(p,incoming);return t?clamp((incoming.start+t.duration/2-c.start-local)/(t.duration/2),0,1):1;}
function applyDissolve(p,id,requested=1,type='dissolve'){const to=p.clips.find(c=>c.id===id&&c.track==='video');if(!to)throw Error('Select a video clip.');const candidates=p.clips.filter(c=>c.track==='video'&&lane(c)===lane(to)&&c.id!==id&&c.start<to.start).sort((a,b)=>b.start-a.start);const from=to.transitionIn?p.clips.find(c=>c.id===to.transitionIn.fromId&&c.track==='video')||candidates[0]:candidates[0];if(!from)throw Error('A dissolve needs a previous video clip.');const max=Math.min(10,clipDuration(from)/2,clipDuration(to)/2);if(max<.05)throw Error('These clips are too short for a dissolve.');const d=clamp(requested,.05,max),oldStart=to.start,nextStart=from.start+clipDuration(from)-d,delta=nextStart-oldStart;for(const c of p.clips)if(c.track==='video'&&lane(c)===lane(to)&&c.id!==from.id&&c.start>=oldStart-.0001)c.start=Math.max(0,c.start+delta);to.start=nextStart;to.transitionIn={type:['dissolve','fadeblack'].includes(type)?type:'dissolve',fromId:from.id,duration:d};if(p.clips.indexOf(to)<p.clips.indexOf(from)){p.clips.splice(p.clips.indexOf(to),1);p.clips.splice(p.clips.indexOf(from)+1,0,to);}return to.transitionIn;}
function removeDissolve(p,id){const to=p.clips.find(c=>c.id===id);if(!to?.transitionIn)return;const t=transitionFor(p,to);if(t){const old=to.start,delta=t.from.start+clipDuration(t.from)-old;for(const c of p.clips)if(c.track==='video'&&lane(c)===lane(to)&&c.id!==t.from.id&&c.start>=old-.0001)c.start+=delta;}delete to.transitionIn;}
function normalizeProject(raw){if(!raw||raw.version!==1||!Array.isArray(raw.assets)||!Array.isArray(raw.clips))throw Error('This is not a supported Crazyland Motion project.');if(raw.assets.length>500||raw.clips.length>2000)throw Error('Project is too large.');const p=newProject();p.name=String(raw.name||'Untitled project').slice(0,120);p.ratio=['16:9','9:16','1:1','4:3'].includes(raw.ratio)?raw.ratio:'16:9';p.fps=[24,25,30,60].includes(raw.fps)?raw.fps:30;p.assets=raw.assets.map(a=>({id:String(a.id),path:String(a.path),name:String(a.name||''),type:a.type}));p.timeline={magnetic:raw.timeline?.magnetic===true,linkage:raw.timeline?.linkage!==false,snapping:raw.timeline?.snapping!==false};p.trackStates=Object.fromEntries(Object.entries(raw.trackStates||{}).filter(([k])=>/^(video|text|audio):(?:[0-9]|1[0-5])$/.test(k)).map(([k,v])=>[k,{locked:!!v?.locked,hidden:!!v?.hidden,muted:!!v?.muted}]));p.clips=raw.clips.map(c=>{if(!['video','audio','text'].includes(c.track))throw Error('Invalid track.');return {...c,id:String(c.id),assetId:c.assetId?String(c.assetId):undefined,start:clamp(c.start,0,86400),in:clamp(c.in,0,86400),out:clamp(c.out,0,86400),speed:clamp(c.speed||1,.25,4),volume:clamp(c.volume,0,2),scale:clamp(c.scale||1,.1,3),x:clamp(c.x,-1,1),y:clamp(c.y,-1,1),rotation:clamp(c.rotation,-180,180),brightness:clamp(c.brightness,-1,1),contrast:clamp(c.contrast??1,0,3),saturation:clamp(c.saturation??1,0,3),fadeIn:clamp(c.fadeIn,0,86400),fadeOut:clamp(c.fadeOut,0,86400),audioFadeIn:clamp(c.audioFadeIn??c.fadeIn,0,86400),audioFadeOut:clamp(c.audioFadeOut??c.fadeOut,0,86400),audioMuted:!!c.audioMuted,transitionIn:['dissolve','fadeblack'].includes(c.transitionIn?.type)?{type:c.transitionIn.type,fromId:String(c.transitionIn.fromId),duration:clamp(c.transitionIn.duration,.05,10)}:undefined,text:String(c.text||'').slice(0,2000),fontSize:clamp(c.fontSize||64,12,180),color:/^#[0-9a-f]{6}$/i.test(c.color)?c.color:'#ffffff',bold:!!c.bold,opacity:clamp(c.opacity??1,0,1),keyframes:normalizeKeyframes(c.keyframes),fontFamily:Object.hasOwn(fonts,c.fontFamily)?c.fontFamily:'Arial',strokeWidth:clamp(c.strokeWidth,0,12),strokeColor:/^#[0-9a-f]{6}$/i.test(c.strokeColor)?c.strokeColor:'#000000',background:!!c.background,backgroundColor:/^#[0-9a-f]{6}$/i.test(c.backgroundColor)?c.backgroundColor:'#15151b',shadow:c.shadow!==false,lane:Number.isFinite(c.lane)?Math.round(clamp(c.lane,0,15)):undefined,groupId:c.groupId?String(c.groupId).slice(0,100):undefined,anchorId:c.anchorId?String(c.anchorId).slice(0,100):undefined,disabled:!!c.disabled};});for(const c of p.clips){if(c.out<=c.in)throw Error('A clip has an invalid duration.');if(c.track!=='text'&&!p.assets.some(a=>a.id===c.assetId))throw Error('A clip references missing media.');}assignLegacyLanes(p);return p;}
function dimensions(ratio,height=1080){const [w,h]=ratio.split(':').map(Number);return {width:Math.round(height*w/h/2)*2,height};}
function timecode(t,fps=30){t=Math.max(0,t);return [Math.floor(t/3600),Math.floor(t/60)%60,Math.floor(t)%60,Math.floor(t%1*fps+1e-5)].map(n=>String(n).padStart(2,'0')).join(':');}
return {arrangeVideo,lane,trackKey,trackState,isMain,frameTime,orderedClips,availableLane,assignLegacyLanes,mainSequence,captureAnchors,reflowMain,reorderMain,insertionIndex,snapPlacement,removeTimelineClips,animatedKeys,fonts,propertyAt,evaluated,setKeyframe,propertyExpression,reframeKeyframes,motionPreset,rippleDelete,outgoingTransitionGain,uid,clamp,clipDuration,duration,active,newProject,createClip,createText,splitClip,transitionFor,videoGain,applyDissolve,removeDissolve,fadeDurations,fadeGain,audioGain,detachAudio,normalizeProject,dimensions,timecode};
});
