'use strict';
const C=window.EditorCore,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const icon=name=>'<svg><use href="#i-'+name+'"/></svg>';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=window.desktop;
let project=C.newProject(),selected=null,tab='media',inspectorTab='video',time=0,playing=false,muted=false,zoom=40,dirty=false,exporting=false;
let history=[],future=[],media=new Map(),toastTimer,playStart=0,playTime=0,lastDraw=0;
const canvas=$('#preview-canvas'),ctx=canvas.getContext('2d');
function toast(message,timeout=4500){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,timeout);}
function error(e){toast(String(e.message||e).replace(/^Error invoking remote method '[^']+': Error: /,''),8000);}
function snapshot(){return JSON.stringify({clips:project.clips,name:project.name,ratio:project.ratio,fps:project.fps});}
function remember(){history.push(snapshot());if(history.length>60)history.shift();future=[];}
function changed(){dirty=true;$('#save-state').textContent='Unsaved changes';updateButtons();}
function restore(s){Object.assign(project,JSON.parse(s));if(!project.clips.some(c=>c.id===selected))selected=null;time=Math.min(time,C.duration(project));changed();renderAll();seek(time);}
function undo(){if(!history.length)return;pause();future.push(snapshot());restore(history.pop());}
function redo(){if(!future.length)return;pause();history.push(snapshot());restore(future.pop());}
function selection(){return project.clips.find(c=>c.id===selected);}
function updateButtons(){const c=selection();$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;for(const id of ['split','duplicate','delete','ripple-delete'])$('#'+id).disabled=!c;$('#export-button').disabled=!project.clips.length;$('#play-button').disabled=!project.clips.length;$('#selection-status').textContent=c?(c.track==='text'?'Text':project.assets.find(a=>a.id===c.assetId)?.name||'Clip')+' selected':'No clip selected';}
function setSelected(id){selected=id;inspectorTab=selection()?.track==='text'?'text':selection()?.track==='audio'?'audio':'video';renderInspector();renderTimeline();updateButtons();draw();}
function clearMedia(){for(const el of media.values()){if(el.pause)el.pause();if(el.src){el.removeAttribute('src');el.load?.();}}media.clear();}
function element(c){if(media.has(c.id))return media.get(c.id);const a=project.assets.find(a=>a.id===c.assetId);if(!a)return null;let el;if(a.type==='image'){el=new Image();el.onload=draw;el.src=a.src;}else{el=document.createElement(a.type==='audio'?'audio':'video');el.preload='auto';el.src=a.src;el.addEventListener('seeked',draw);el.addEventListener('loadeddata',()=>{syncMedia();draw();});el.addEventListener('error',()=>toast('Preview cannot play '+a.name+'. You can still try exporting with FFmpeg.',7000));}media.set(c.id,el);return el;}
function fade(c){return C.videoGain(project,c,time-c.start);}
function syncMedia(){const active=new Set();for(const c of project.clips){if(c.track==='text')continue;const isActive=!c.disabled&&time>=c.start&&time<c.start+C.clipDuration(c);if(!isActive)continue;active.add(c.id);const el=element(c);if(!el||el instanceof HTMLImageElement)continue;const target=c.in+(time-c.start)*(c.speed||1);if(Number.isFinite(el.duration)&&Math.abs(el.currentTime-target)>(playing?.25:.02)){try{el.currentTime=Math.min(target,Math.max(0,el.duration-.001));}catch{}}el.playbackRate=c.speed||1;el.volume=C.clamp(C.audioGain(c,time-c.start),0,1);el.muted=muted||C.trackState(project,c).muted||c.disabled;if(playing&&el.paused)el.play().catch(()=>{});if(!playing&&!el.paused)el.pause();}
for(const [id,el]of media){if(!active.has(id)&&el.pause&&!el.paused)el.pause();}}
function resizeCanvas(){const d=C.dimensions(project.ratio);if(canvas.width!==d.width||canvas.height!==d.height){canvas.width=d.width;canvas.height=d.height;}$('#preview-size').textContent=d.width+' × '+d.height;$('#aspect-ratio').value=project.ratio;const [rw,rh]=project.ratio.split(':').map(Number);const area=$('#preview-area');const w=Math.max(100,area.clientWidth-64),h=Math.max(100,area.clientHeight-48);const width=Math.min(w,h*rw/rh);$('.canvas-wrap').style.width=width+'px';$('.canvas-wrap').style.aspectRatio=rw+'/'+rh;draw();}
function draw(){const W=canvas.width,H=canvas.height;ctx.fillStyle='#0b0c0f';ctx.fillRect(0,0,W,H);for(const c of C.active(project,time,'video')){const a=project.assets.find(a=>a.id===c.assetId),el=element(c);if(!a||!el||(a.type==='image'?!el.complete:el.readyState<2))continue;const v=C.evaluated(c,time-c.start);const fit=Math.min(W/a.width,H/a.height)*(c.scale||1);ctx.save();ctx.translate(W/2+v.x*W,H/2+v.y*H);ctx.rotate((c.rotation||0)*Math.PI/180);ctx.globalAlpha=C.clamp(fade(c),0,1);ctx.filter='brightness('+(1+(c.brightness||0))+') contrast('+(c.contrast??1)+') saturate('+(c.saturation??1)+')';try{ctx.drawImage(el,-a.width*fit/2,-a.height*fit/2,a.width*fit,a.height*fit);}catch{}ctx.restore();}
for(const c of C.active(project,time,'text')){const v=C.evaluated(c,time-c.start);ctx.save();const size=c.fontSize*H/1080;ctx.font=(c.bold?'bold ':'')+size+'px '+(c.fontFamily||'Arial');ctx.globalAlpha=v.opacity;ctx.textAlign='center';ctx.textBaseline='middle';const lines=c.text.split('\n'),x=W/2+v.x*W,y=H/2+v.y*H,pad=12*H/1080;if(c.background){const width=Math.max(...lines.map(line=>ctx.measureText(line).width));ctx.fillStyle=c.backgroundColor;ctx.fillRect(x-width/2-pad,y-lines.length*size*1.2/2-pad,width+pad*2,lines.length*size*1.2+pad*2);}ctx.shadowColor=c.shadow===false?'transparent':'#0009';ctx.shadowBlur=0;ctx.shadowOffsetX=c.shadow===false?0:2;ctx.shadowOffsetY=c.shadow===false?0:2;ctx.fillStyle=c.color;ctx.strokeStyle=c.strokeColor||'#000000';ctx.lineWidth=(c.strokeWidth||0)*2*H/1080;ctx.lineJoin='round';lines.forEach((line,i)=>{const ly=y+(i-(lines.length-1)/2)*size*1.2;if(c.strokeWidth)ctx.strokeText(line,x,ly);ctx.fillText(line,x,ly);});ctx.restore();}
$('#preview-empty').hidden=project.clips.length>0;renderPreviewSelection();
}
function updateTime(){const duration=C.duration(project);$('#current-time').textContent=C.timecode(time,project.fps);$('#total-time').textContent=C.timecode(duration,project.fps);$('#playhead').style.left=time*zoom+'px';$('#fps-label').textContent=project.fps+' fps';}
function seek(t){time=C.clamp(t,0,C.duration(project));if(playing){playTime=time;playStart=performance.now();}syncMedia();draw();updateTime();if(inspectorTab==='motion')renderKeyframeStatus();}
function pause(){playing=false;for(const el of media.values())el.pause?.();$('#play-button').innerHTML=icon('play');$('#play-button').setAttribute('aria-label','Play');}
function play(){if(!project.clips.length)return;if(playing){pause();return;}if(time>=C.duration(project)-.01)time=0;playing=true;playTime=time;playStart=performance.now();$('#play-button').innerHTML=icon('pause');$('#play-button').setAttribute('aria-label','Pause');syncMedia();requestAnimationFrame(tick);}
function tick(now){if(!playing)return;time=playTime+(now-playStart)/1000;if(time>=C.duration(project)){time=C.duration(project);pause();syncMedia();draw();updateTime();return;}if(now-lastDraw>=1000/project.fps){lastDraw=now;syncMedia();draw();updateTime();const scroll=$('#timeline-scroll');const x=time*zoom;if(x>scroll.scrollLeft+scroll.clientWidth-40)scroll.scrollLeft=x-scroll.clientWidth/2;}requestAnimationFrame(tick);}
async function importMedia(files){if(!api){toast('Launch the desktop app to import local media.');return;}$('#import-button').disabled=true;$('#import-button').innerHTML=icon('upload')+'Importing…';try{const result=files?await api.importDropped(files):await api.importMedia();project.assets.push(...result.assets);if(result.assets.length){changed();renderLibrary();toast(result.assets.length+' file'+(result.assets.length===1?'':'s')+' imported. Click + or drag to the timeline.');}if(result.errors.length)toast(result.errors.join('\n'),9000);}catch(e){error(e);}finally{$('#import-button').disabled=false;$('#import-button').innerHTML=icon('plus')+'Import media<span>Ctrl I</span>';}}
function addAsset(id,start,track){const a=project.assets.find(a=>a.id===id);if(!a)return;if(!track&&tab==='audio'&&a.hasAudio)track='audio';if(track==='text'||(track==='audio'&&!a.hasAudio)||(track==='video'&&a.type==='audio')){toast('Choose the '+(a.type==='audio'?'audio':'video')+' track for this file.');return;}remember();const c=C.createClip(a,start??Math.max(0,...project.clips.filter(c=>c.track===(track||(a.type==='audio'?'audio':'video'))).map(c=>c.start+C.clipDuration(c))));if(track)c.track=track;project.clips.push(c);selected=c.id;inspectorTab=c.track;changed();renderAll();seek(c.start);}
function addText(preset='title'){remember();const c=C.createText(time);if(preset==='subtitle'){c.text='Add a little context';c.fontSize=40;c.y=.37;c.bold=false;}if(preset==='subtitle'){c.strokeWidth=2;c.shadow=false;}if(preset==='editorial'){c.text='A story worth telling';c.fontFamily='Georgia';c.fontSize=82;c.y=0;c.bold=false;}if(preset==='badge'){c.text='THE NEXT CHAPTER';c.fontSize=34;c.y=.32;c.background=true;c.backgroundColor='#573e79';c.shadow=false;}if(preset==='label'){c.text='A MOMENT WORTH KEEPING';c.fontSize=30;c.y=-.35;}project.clips.push(c);selected=c.id;inspectorTab='text';changed();renderAll();seek(time);}
function renderLibrary(){const titles={media:'Project media',audio:'Your audio',text:'Titles & typography',motion:'Bring it to life',transitions:'Between the scenes',filters:'Color looks'};$('#library-title').textContent=titles[tab];$('#media-tools').hidden=!['media','audio'].includes(tab);$('#media-count').hidden=!['media','audio'].includes(tab);$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const container=$('#library-content');
if(tab==='text'){container.innerHTML='<p class="library-note">Add a title, then make it yours in the inspector.</p><button class="text-preset" data-text-preset="title"><strong>Your story</strong><span>Title · bold and simple</span></button><button class="text-preset" data-text-preset="subtitle"><strong style="font-size:17px;font-weight:400">A little more to say</strong><span>Subtitle · the finishing touch</span></button><button class="text-preset" data-text-preset="label"><strong style="font-size:13px;letter-spacing:2px">THE SMALL DETAILS</strong><span>Label · set the scene</span></button><button class="text-preset" data-text-preset="editorial"><strong style="font-family:Georgia;font-weight:400">Worth telling</strong><span>Editorial · classic serif</span></button><button class="text-preset" data-text-preset="badge"><strong style="font-size:13px;background:#573e79;padding:8px">THE NEXT CHAPTER</strong><span>Badge · a colored backdrop</span></button>';return;}
if(tab==='motion'){container.innerHTML='<p class="library-note">Select a video or title. Presets create editable position and opacity keyframes.</p><div class="preset-grid">'+[['fade','Fade in','A quiet entrance'],['slide','Slide across','Move into the scene'],['rise','Rise up','Lift and reveal'],['none','Clear motion','Return to a still frame']].map(([id,label,note])=>'<button class="motion-card" data-motion="'+id+'"><span class="motion-demo '+id+'"><i></i></span><strong>'+label+'</strong><small>'+note+'</small></button>').join('')+'</div>';return;}
if(tab==='transitions'){container.innerHTML='<p class="library-note">Select the second of two video clips. A transition overlaps the cut and keeps following video in sequence.</p>'+[['dissolve','Cross dissolve','Blend one scene into the next'],['fadeblack','Fade through black','A pause between two moments']].map(([id,label,note])=>'<button class="transition-card" data-transition-preset="'+id+'"><span class="transition-demo '+id+'"><i></i><i></i></span><strong>'+label+'</strong><small>'+note+'</small></button>').join('');return;}
if(tab==='filters'){container.innerHTML='<p class="library-note">Select a video clip to apply a look. Fine-tune it under Color.</p><div class="filter-grid">'+[['Original',0,1,1],['Vivid',.02,1.15,1.5],['Mono',0,1.15,0],['Soft',.03,.85,.8],['Cinema',-.05,1.25,.8],['Bright',.15,1,1.1]].map(([n,b,c,s])=>'<button class="filter-preset" data-filter="'+[b,c,s].join(',')+'"><span class="filter-swatch" style="filter:brightness('+(1+b)+') contrast('+c+') saturate('+s+')"></span>'+n+'</button>').join('')+'</div>';return;}
const query=$('#search-media').value.toLowerCase();const list=project.assets.filter(a=>(tab!=='audio'||a.hasAudio)&&a.name.toLowerCase().includes(query));$('#media-count').textContent=list.length;
if(!list.length){container.innerHTML='<div class="library-empty">'+icon(tab==='audio'?'music':'upload')+'<h3>'+(query?'No matching files':tab==='audio'?'Find your soundtrack':'Your media lives here')+'</h3><p>'+(query?'Try another file name.':tab==='audio'?'Import music or sound effects to give your edit a rhythm.':'Import a few clips, then drag them onto the timeline.')+'</p></div>';return;}
container.innerHTML='<div class="media-grid">'+list.map(a=>'<div class="media-card" draggable="true" data-asset="'+esc(a.id)+'" tabindex="0" role="button" aria-label="Add '+esc(a.name)+' to timeline"><div class="media-thumb">'+(a.thumbnail?'<img src="'+a.thumbnail+'" alt="">':icon('music'))+'<span class="duration">'+(a.type==='image'?'IMAGE':Math.floor(a.duration/60)+':'+String(Math.floor(a.duration)%60).padStart(2,'0'))+'</span><button data-add="'+esc(a.id)+'" aria-label="Add '+esc(a.name)+'">'+icon('plus')+'</button></div><h3>'+esc(a.name)+'</h3><p>'+(a.type==='audio'?'Audio':a.width+' × '+a.height)+(a.type==='video'?' · Video':'')+'</p></div>').join('')+'</div>';
}
function waveform(a,c,width){if(!a?.waveform?.length)return '';const samples=Math.max(20,Math.min(240,Math.round(width/3))),sampleDuration=a.waveformDuration||Math.min(a.duration,120);const dur=C.clipDuration(c);let paths='';for(let i=0;i<samples;i++){const local=(i+.5)/samples*dur,source=c.in+local*(c.speed||1);const index=Math.floor(source/sampleDuration*a.waveform.length);const peak=(index>=0&&index<a.waveform.length?a.waveform[index]:0)*C.audioGain(c,local);const x=(i+.5)/samples*300;paths+='<path d="M'+x.toFixed(2)+' '+(12-peak*10).toFixed(2)+'v'+Math.max(.5,peak*20).toFixed(2)+'"/>';}return '<svg class="waveform" viewBox="0 0 300 24" preserveAspectRatio="none" aria-hidden="true">'+paths+'</svg>';}
function audioVisuals(c,a,width){const dur=C.clipDuration(c),f=C.fadeDurations(c),height=49,bottom=47,level=24;const envelope=[];for(let i=0;i<=64;i++){const local=i/64*dur;envelope.push((i/64*width).toFixed(2)+','+(bottom-C.audioGain(c,local)*level).toFixed(2));}const left=f.in/dur*width,right=width-f.out/dur*width,y=bottom-(c.audioMuted?0:c.volume??1)*level;
let markup='<svg class="audio-envelope" viewBox="0 0 '+width+' '+height+'" preserveAspectRatio="none" aria-hidden="true"><polygon class="envelope-fill" points="0,'+bottom+' '+envelope.join(' ')+' '+width+','+bottom+'"/><polyline class="envelope-line" points="'+envelope.join(' ')+'"/><path class="audio-volume-target" data-volume-handle="true" d="M0 '+y+'H'+width+'"/></svg>';
markup+='<span class="clip-audio-status">'+(c.audioMuted?'Muted':Math.round((c.volume??1)*100)+'%')+'</span>';
for(const side of ['in','out']){const seconds=f[side],x=side==='in'?left:right;const label='Fade '+side+': '+seconds.toFixed(2)+' seconds';markup+='<button class="timeline-fade-handle '+side+'" data-fade="'+side+'" style="left:'+Math.max(7,Math.min(width-7,x))+'px;top:'+Math.max(22,y)+'px" title="'+label+' · drag to adjust" role="slider" aria-label="Audio fade '+side+'" aria-valuemin="0" aria-valuemax="'+dur.toFixed(2)+'" aria-valuenow="'+seconds.toFixed(2)+'" aria-valuetext="'+label+'"></button>';if(seconds>0)markup+='<span class="fade-region '+side+'" style="'+(side==='in'?'left:0':'right:0')+';width:'+Math.max(1,seconds/dur*width)+'px" title="'+label+'"><span>'+seconds.toFixed(1)+'s</span></span>';}
return markup;
}
function transitionVisuals(c,width){if(!c.transitionIn)return '';const t=C.transitionFor(project,c);if(!t)return '<span class="transition-disconnected" title="Move this clip to overlap the previous clip, or remove its transition.">Transition disconnected</span>';const px=t.duration/C.clipDuration(c)*width;return '<span class="transition-region" style="width:'+px+'px" title="'+(t.type==='fadeblack'?'Fade through black':'Cross dissolve')+' · '+t.duration.toFixed(2)+' seconds"><span>⋈ '+t.duration.toFixed(1)+'s</span></span><button class="transition-duration-handle" data-transition-handle style="left:'+12+'px" role="slider" aria-label="Dissolve duration" aria-valuemin="0.05" aria-valuemax="'+Math.min(10,C.clipDuration(c)/2,C.clipDuration(t.from)/2)+'" aria-valuenow="'+t.duration.toFixed(2)+'" title="Dissolve '+t.duration.toFixed(2)+'s · drag to adjust">⋈</button>';}
function changeTransition(seconds){const c=selection();if(!c)return;const before=snapshot();try{C.applyDissolve(project,c.id,seconds,c.transitionIn?.type||'dissolve');history.push(before);future=[];changed();renderTimeline();renderInspector();syncMedia();draw();}catch(e){toast(e.message);}}
function renderTimeline(){const d=C.duration(project);time=Math.min(time,d);const w=Math.max($('#timeline-scroll').clientWidth-1,(d+8)*zoom);$('#timeline-surface').style.width=w+'px';let step=zoom>=80?1:zoom>=35?2:zoom>=15?5:10;let html='';for(let s=0;s<=w/zoom;s+=step)html+='<div class="ruler-tick" style="left:'+s*zoom+'px"><span>'+Math.floor(s/60)+':'+String(s%60).padStart(2,'0')+'</span></div>';$('#ruler').innerHTML=html;
$$('.track').forEach(track=>{const clips=project.clips.filter(c=>c.track===track.dataset.track),ends=[],lanes=new Map();for(const c of [...clips].sort((a,b)=>a.start-b.start)){let lane=ends.findIndex(end=>end<=c.start+.00001);if(lane<0)lane=ends.length;ends[lane]=c.start+C.clipDuration(c);lanes.set(c.id,lane);}const laneCount=Math.max(1,ends.length);track.style.height=laneCount*67+'px';const label=$$('.track-label')[$$('.track').indexOf(track)];label.style.height=laneCount*67+'px';label.querySelector('.lane-count')?.remove();if(laneCount>1)label.insertAdjacentHTML('beforeend','<span class="lane-count">'+laneCount+' layers</span>');track.innerHTML=clips.map(c=>{const a=project.assets.find(a=>a.id===c.assetId);return '<div class="timeline-clip '+c.track+(c.id===selected?' selected':'')+(c.track==='audio'&&c.audioMuted?' audio-muted':'')+'" data-clip="'+esc(c.id)+'" style="top:'+(9+lanes.get(c.id)*67)+'px;left:'+c.start*zoom+'px;width:'+Math.max(8,C.clipDuration(c)*zoom)+'px" tabindex="0" role="button" aria-label="'+esc(c.track==='text'?c.text:a?.name)+'"><div class="clip-handle left" data-handle="left"></div>'+(a?.thumbnail&&c.track==='video'?'<div class="filmstrip" style="background-image:url('+a.thumbnail+')"></div>':'')+'<div class="clip-label">'+icon(c.track==='text'?'text':c.track==='audio'?'music':'media')+esc(c.track==='text'?c.text:a?.name||'Clip')+'</div>'+(c.track==='audio'?waveform(a,c,Math.max(8,C.clipDuration(c)*zoom))+audioVisuals(c,a,Math.max(8,C.clipDuration(c)*zoom)):'')+(c.track==='video'&&(c.fadeIn||c.fadeOut)?'<span class="video-fade-badge">Video fade '+Number(c.fadeIn||c.fadeOut).toFixed(1)+'s</span>':'')+(c.track==='video'?transitionVisuals(c,Math.max(8,C.clipDuration(c)*zoom)):'')+(c.track==='video'&&c.audioMuted?'<span class="video-mute-badge">Audio muted</span>':'')+(c.keyframes||[]).filter(f=>f.time<=C.clipDuration(c)).map((f,i)=>'<button class="keyframe-diamond" data-timeline-keyframe="'+i+'" style="left:'+Math.max(7,Math.min(C.clipDuration(c)*zoom-7,f.time*zoom))+'px" title="Keyframe '+C.timecode(f.time,project.fps)+'" aria-label="Jump to keyframe"></button>').join('')+'<div class="clip-handle right" data-handle="right"></div></div>';}).join('');});
$('#timeline-empty').hidden=project.clips.length>0;$('#timeline-status').textContent=project.clips.length?project.clips.length+' clips · '+C.timecode(d,project.fps):'Ready when you are';updateTime();updateButtons();}
function range(key,label,min,max,step,format){const c=selection(),value=C.animatedKeys.includes(key)?C.propertyAt(c,key,keyframeLocal(c)):c[key];return '<div class="range-label"><label for="prop-'+key+'">'+label+'</label><output data-value="'+key+'">'+(format?format(value):value)+'</output></div><input id="prop-'+key+'" type="range" data-prop="'+key+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(value??0)+'">';}
function number(key,label,step=0.1,min,max){const c=selection();return '<label class="field">'+label+'<input type="number" data-prop="'+key+'" value="'+(c[key]??0)+'" step="'+step+'"'+(min!==undefined?' min="'+min+'"':'')+(max!==undefined?' max="'+max+'"':'')+'></label>';}
function renderInspector(){const c=selection(),container=$('#inspector-content');$('#reset-clip').hidden=!c;if(!c){container.innerHTML='<div class="inspector-empty">'+icon('filter')+'<h3>A little fine-tuning</h3><p>Select a clip on the timeline<br>to make it your own.</p></div><div class="project-info"><h3>Project settings</h3><div class="info-row"><span>Aspect ratio</span><strong>'+project.ratio+'</strong></div><div class="info-row"><span>Frame rate</span><strong>'+project.fps+' fps</strong></div><div class="info-row"><span>Duration</span><strong>'+C.timecode(C.duration(project),project.fps)+'</strong></div><div class="info-row"><span>Media files</span><strong>'+project.assets.length+'</strong></div></div>';return;}
const a=project.assets.find(a=>a.id===c.assetId);const tabs=c.track==='text'?['text','motion']:c.track==='audio'?['audio','motion']:['video','audio','color','motion'];if(!tabs.includes(inspectorTab))inspectorTab=tabs[0];let html='<h3 class="selected-name">'+esc(c.track==='text'?'Title layer':a?.name||'Clip')+'</h3><div class="inspector-tabs">'+tabs.map(t=>'<button data-inspector="'+t+'" class="'+(t===inspectorTab?'active':'')+'">'+t[0].toUpperCase()+t.slice(1)+'</button>').join('')+'</div>';
if(inspectorTab==='text'){html+='<label class="field">Text<textarea data-prop="text">'+esc(c.text)+'</textarea></label><div class="field-grid">'+number('fontSize','Size',1,12,180)+'<label class="field">Color<input type="color" data-prop="color" value="'+c.color+'"></label></div><label class="checkbox-field"><input type="checkbox" data-prop="bold" '+(c.bold?'checked':'')+'>Bold</label><div class="property-section"><h3>Position</h3>'+range('x','Horizontal',-1,1,.01,v=>Math.round(v*100)+'%')+range('y','Vertical',-1,1,.01,v=>Math.round(v*100)+'%')+'</div>';}
if(inspectorTab==='text'){html+='<div class="property-section"><h3>Typography</h3><label class="field">Font<select data-prop="fontFamily">'+Object.keys(C.fonts).map(f=>'<option '+(f===(c.fontFamily||'Arial')?'selected':'')+'>'+f+'</option>').join('')+'</select></label><div class="field-grid">'+number('strokeWidth','Outline',1,0,12)+'<label class="field">Outline color<input type="color" data-prop="strokeColor" value="'+(c.strokeColor||'#000000')+'"></label></div><div class="style-toggles"><label class="checkbox-field"><input type="checkbox" data-prop="shadow" '+(c.shadow!==false?'checked':'')+'>Shadow</label><label class="checkbox-field"><input type="checkbox" data-prop="background" '+(c.background?'checked':'')+'>Background</label></div><label class="field">Background color<input type="color" data-prop="backgroundColor" value="'+(c.backgroundColor||'#15151b')+'"></label></div>';}
if(inspectorTab==='motion'){html+=motionInspector(c);}
if(inspectorTab==='video'){html+='<div class="property-section"><h3>Transform</h3>'+range('scale','Scale',.1,3,.01,v=>Math.round(v*100)+'%')+range('rotation','Rotation',-180,180,1,v=>v+'°')+range('x','Horizontal',-1,1,.01,v=>Math.round(v*100)+'%')+range('y','Vertical',-1,1,.01,v=>Math.round(v*100)+'%')+'</div><div class="property-section"><h3>Playback</h3>'+range('speed','Speed',.25,4,.25,v=>v+'×')+'</div>';html+='<div class="property-section"><h3>Transition in</h3>'+(c.transitionIn?'<label class="field">Transition duration (s)<input type="number" data-transition-duration min=".05" max="10" step=".1" value="'+(C.transitionFor(project,c)?.duration||c.transitionIn.duration).toFixed(2)+'"></label><button class="text-button" data-remove-transition>Remove transition</button>':'<button class="button" data-add-transition>⋈ Cross dissolve</button>')+'<p class="inspector-hint">Overlap this clip with the preceding video. Later video clips shift to keep the edit together; music and text stay in place.</p></div>';}
if(inspectorTab==='audio'){html+='<div class="property-section"><h3>Sound</h3>'+range('volume','Volume',0,1,.01,v=>Math.round(v*100)+'%')+'<label class="checkbox-field"><input type="checkbox" data-prop="audioMuted" '+(c.audioMuted?'checked':'')+'>Mute this clip</label>'+(a?.hasAudio?'<div class="audio-fade-controls"><h3>Music fades</h3><div class="field-grid">'+number('audioFadeIn','Fade in (s)',.1,0,C.clipDuration(c))+number('audioFadeOut','Fade out (s)',.1,0,C.clipDuration(c))+'</div><div class="fade-presets"><button data-fade-preset="0">None</button><button data-fade-preset="0.5">0.5s</button><button data-fade-preset="1">1s</button><button data-fade-preset="2">2s</button></div><p class="inspector-hint">Drag the circular handles on an audio clip to shape its fades. Drag its volume line to change the level.</p></div>':'<p class="inspector-hint">This clip has no audio.</p>')+(c.track==='video'&&a?.hasAudio?'<button class="button detach-button" data-detach-audio>'+icon('music')+'Extract audio</button>':'')+'</div>';}
if(inspectorTab==='color'){html+='<div class="property-section"><h3>Adjustments</h3>'+range('brightness','Brightness',-.5,.5,.01,v=>Math.round(v*100))+range('contrast','Contrast',0,3,.01,v=>Math.round(v*100)+'%')+range('saturation','Saturation',0,3,.01,v=>Math.round(v*100)+'%')+'</div>';}
html+='<div class="property-section"><h3>Timing</h3><div class="field-grid">'+number('start','Start (s)',.1,0)+number('duration','Duration (s)',.1,.1)+'</div>'+(c.track!=='text'?'<div class="field-grid">'+number('in','In point (s)',.1,0)+number('out','Out point (s)',.1,0)+'</div>'+(c.track==='video'&&inspectorTab==='video'?'<div class="field-grid">'+number('fadeIn','Video fade in (s)',.1,0,C.clipDuration(c))+number('fadeOut','Video fade out (s)',.1,0,C.clipDuration(c))+'</div>':''):'')+'</div>';
container.innerHTML=html;const dur=container.querySelector('[data-prop="duration"]');if(dur)dur.value=Math.round(C.clipDuration(c)*100)/100;renderKeyframeStatus();
}
function renderAll(){renderLibrary();renderTimeline();renderInspector();$('#project-name').value=project.name;resizeCanvas();}
function rippleDelete(){if(!selection())return;remember();pause();C.rippleDelete(project,selected);selected=null;changed();renderAll();seek(time);toast('Gap closed on this track.');}
function deleteClip(){const c=selection();if(!c)return;remember();pause();project.clips=project.clips.filter(x=>x.id!==c.id);media.get(c.id)?.pause?.();media.delete(c.id);selected=null;changed();renderAll();seek(Math.min(time,C.duration(project)));}
function duplicateClip(){const c=selection();if(!c)return;remember();const copy={...JSON.parse(JSON.stringify(c)),transitionIn:undefined,id:C.uid(),start:c.start+C.clipDuration(c)};project.clips.splice(project.clips.indexOf(c)+1,0,copy);selected=copy.id;changed();renderAll();seek(copy.start);}
function split(){if(!selection())return;const current=selection(),transition=C.transitionFor(project,current);if(transition&&time>current.start&&time<current.start+transition.duration){toast('Split outside the dissolve region, or remove the dissolve first.');return;}const old=snapshot();const right=C.splitClip(project,selected,time);if(!right){toast('Place the playhead inside the selected clip to split.');return;}history.push(old);future=[];selected=right.id;changed();renderAll();syncMedia();}
function snapTime(value,id){value=Math.max(0,value);if(!$('#snap-toggle').checked)return value;const targets=[0,time,...project.clips.filter(c=>c.id!==id).flatMap(c=>[c.start,c.start+C.clipDuration(c)])];const near=targets.find(t=>Math.abs(value-t)<7/zoom);return near??value;}
function timelineAt(event){const r=$('#timeline-surface').getBoundingClientRect();return Math.max(0,(event.clientX-r.left)/zoom);}
let drag=null;
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});
document.addEventListener('drop',e=>{e.preventDefault();if(!e.target.closest('.track')&&e.dataTransfer.files.length)importMedia(e.dataTransfer.files);});
$('#library-content').addEventListener('dragstart',e=>{const card=e.target.closest('[data-asset]');if(card){e.dataTransfer.setData('application/x-cutline-media',card.dataset.asset);e.dataTransfer.effectAllowed='copy';}});
$('#library-content').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b){addAsset(b.dataset.add);return;}const preset=e.target.closest('[data-text-preset]');if(preset){addText(preset.dataset.textPreset);return;}const f=e.target.closest('[data-filter]');if(f){const c=selection();if(c?.track!=='video'){toast('Select a video clip first.');return;}remember();[c.brightness,c.contrast,c.saturation]=f.dataset.filter.split(',').map(Number);inspectorTab='color';changed();renderInspector();draw();}});
$('#library-content').addEventListener('dblclick',e=>{const card=e.target.closest('[data-asset]');if(card)addAsset(card.dataset.asset);});
$('#library-content').addEventListener('keydown',e=>{if(e.key==='Enter'){const card=e.target.closest('[data-asset]');if(card)addAsset(card.dataset.asset);}});
$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderLibrary();$('#library-content').scrollTop=0;});
$('#search-media').oninput=renderLibrary;
$('#inspector-content').addEventListener('click',e=>{
const preset=e.target.closest('[data-fade-preset]'),detach=e.target.closest('[data-detach-audio]');
if(preset){const c=selection();if(!c)return;remember();c.audioFadeIn=c.audioFadeOut=Math.min(Number(preset.dataset.fadePreset),C.clipDuration(c)/2);changed();renderInspector();renderTimeline();syncMedia();}
if(detach){const c=selection();if(!c)return;remember();const audio=C.detachAudio(project,c.id);if(!audio){history.pop();toast('Select a video clip with audio to extract.');return;}selected=audio.id;inspectorTab='audio';changed();renderAll();syncMedia();toast('Audio extracted. The video’s original audio is muted.');}
});
$('#timeline-surface').addEventListener('keydown',e=>{const handle=e.target.closest('[data-fade]');if(!handle||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();e.stopPropagation();const clip=project.clips.find(c=>c.id===handle.closest('[data-clip]').dataset.clip);if(!clip)return;remember();const key=handle.dataset.fade==='in'?'audioFadeIn':'audioFadeOut',step=e.shiftKey?1:.1;clip[key]=C.clamp(e.key==='Home'?0:e.key==='End'?C.clipDuration(clip):(clip[key]||0)+(['ArrowRight','ArrowUp'].includes(e.key)?step:-step),0,C.clipDuration(clip));changed();renderTimeline();renderInspector();syncMedia();$('#timeline-surface [data-clip="'+clip.id+'"] [data-fade="'+handle.dataset.fade+'"]')?.focus();});

$('#inspector-content').addEventListener('click',e=>{if(e.target.closest('[data-add-transition]'))changeTransition(1);if(e.target.closest('[data-remove-transition]')){remember();C.removeDissolve(project,selected);changed();renderAll();syncMedia();}});
$('#inspector-content').addEventListener('change',e=>{if(e.target.matches('[data-transition-duration]')&&Number.isFinite(Number(e.target.value)))changeTransition(Number(e.target.value));});
$('#timeline-surface').addEventListener('keydown',e=>{const handle=e.target.closest('[data-transition-handle]');if(!handle||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();e.stopPropagation();const clip=project.clips.find(c=>c.id===handle.closest('[data-clip]').dataset.clip);setSelected(clip.id);const t=C.transitionFor(project,clip);if(!t)return;changeTransition(e.key==='Home'?.05:e.key==='End'?10:t.duration+(e.key==='ArrowRight'?.1:-.1));$('#timeline-surface [data-clip="'+clip.id+'"] [data-transition-handle]')?.focus();});

let editingProp=null;
$('#inspector-content').addEventListener('pointerdown',e=>{if(e.target.dataset.prop){remember();editingProp=e.target.dataset.prop;}});
$('#inspector-content').addEventListener('focusin',e=>{if(e.target.dataset.prop&&editingProp!==e.target.dataset.prop){remember();editingProp=e.target.dataset.prop;}});
$('#inspector-content').addEventListener('focusout',()=>editingProp=null);
$('#inspector-content').addEventListener('click',e=>{if(e.target.dataset.inspector){inspectorTab=e.target.dataset.inspector;renderInspector();}});
$('#inspector-content').addEventListener('input',e=>{const key=e.target.dataset.prop,c=selection();if(!key||!c)return;let val=e.target.type==='checkbox'?e.target.checked:['text','color','fontFamily','strokeColor','backgroundColor'].includes(key)?e.target.value:Number(e.target.value);if(typeof val==='number'&&!Number.isFinite(val))return;
const original=JSON.parse(JSON.stringify(c));const a=project.assets.find(a=>a.id===c.assetId),max=a?.type!=='image'&&a?a.duration:86400;
if(key==='duration'){c.out=C.clamp(c.in+Math.max(.1,val)*(c.speed||1),c.in+.1,max);}
else if(key==='start')c.start=Math.max(0,val);
else if(key==='in')c.in=C.clamp(val,0,c.out-.1);
else if(key==='out')c.out=C.clamp(val,c.in+.1,max);
else if(['fadeIn','fadeOut','audioFadeIn','audioFadeOut'].includes(key))c[key]=C.clamp(val,0,C.clipDuration(c));
else c[key]=val;
if(['in','out','duration','speed'].includes(key))C.reframeKeyframes(c,original);if(C.animatedKeys.includes(key)&&c.keyframes?.some(f=>key in f.values)){C.setKeyframe(c,C.clamp(time-c.start,0,C.clipDuration(c)),{[key]:val});renderKeyframeStatus();}
const output=$('[data-value="'+key+'"]');if(output)output.textContent=['scale','volume','contrast','saturation'].includes(key)?Math.round(val*100)+'%':['x','y'].includes(key)?Math.round(val*100)+'%':key==='speed'?val+'×':key==='rotation'?val+'°':key==='brightness'?Math.round(val*100):val;changed();renderTimeline();syncMedia();draw();});
$('#reset-clip').onclick=()=>{const c=selection();if(!c)return;remember();const defaults=c.track==='text'?C.createText():C.createClip(project.assets.find(a=>a.id===c.assetId));for(const key of ['scale','x','y','rotation','brightness','contrast','saturation','speed','volume','fadeIn','fadeOut','audioFadeIn','audioFadeOut','audioMuted','fontSize','color','bold','fontFamily','strokeWidth','strokeColor','background','backgroundColor','shadow','opacity','keyframes'])if(key in defaults)c[key]=defaults[key];changed();renderInspector();renderTimeline();syncMedia();draw();};
async function confirmDiscard(){if(!dirty)return true;return new Promise(resolve=>{const d=$('#confirm-dialog');d.showModal();$('#keep-editing').onclick=()=>{d.close();resolve(false);};$('#discard-edits').onclick=()=>{d.close();resolve(true);};d.oncancel=()=>resolve(false);});}
async function newProject(){if(!await confirmDiscard())return;pause();clearMedia();await api?.newProject();project=C.newProject();selected=null;clearTimelineSelection();time=0;history=[];future=[];dirty=false;$('#save-state').textContent='Unsaved';renderAll();}
async function openProject(){if(!api)return;if(!await confirmDiscard())return;try{const p=await api.openProject();if(!p)return;pause();clearMedia();project=p;selected=null;clearTimelineSelection();time=0;history=[];future=[];dirty=false;$('#save-state').textContent='Saved';renderAll();toast('Project opened.');}catch(e){error(e);}}
async function saveProject(saveAs=false){if(!api)return;try{const revision=snapshot();const result=await api.saveProject(project,saveAs);if(!result.cancelled){if(revision===snapshot()){dirty=false;$('#save-state').textContent='Saved';}toast('Project saved.');}}catch(e){error(e);}}
$('#new-project').onclick=newProject;$('#open-project').onclick=openProject;$('#save-project').onclick=()=>saveProject();
$('#project-name').addEventListener('focus',remember);$('#project-name').oninput=e=>{project.name=e.target.value.trim()||'Untitled project';changed();};
$('#aspect-ratio').onchange=e=>{remember();project.ratio=e.target.value;changed();resizeCanvas();renderInspector();};
for(const id of ['import-button','preview-import'])$('#'+id).onclick=()=>importMedia();
$('#play-button').onclick=play;$('#previous-frame').onclick=()=>{pause();seek(time-1/project.fps);};$('#next-frame').onclick=()=>{pause();seek(time+1/project.fps);};
$('#mute-button').onclick=()=>{muted=!muted;$('#mute-button').style.color=muted?'#e18492':'';$('#mute-button').setAttribute('aria-label',muted?'Unmute preview':'Mute preview');syncMedia();};
$('#fullscreen').onclick=()=>{$('#preview-area').requestFullscreen().catch(error);};
document.addEventListener('fullscreenchange',resizeCanvas);new ResizeObserver(resizeCanvas).observe($('#preview-area'));
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#split').onclick=split;$('#duplicate').onclick=duplicateClip;$('#delete').onclick=deleteClip;$('#add-text').onclick=()=>addText();$('#ripple-delete').onclick=rippleDelete;
$('#timeline-zoom').oninput=e=>zoomTimeline(Number(e.target.value));
$('#fit-timeline').onclick=()=>{zoomTimeline(C.clamp(($('#timeline-scroll').clientWidth-45)/Math.max(5,C.duration(project)),.2,240),0,0);};
$('#help-button').onclick=()=>$('#help-dialog').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>{if(!exporting)$('#'+b.dataset.close).close();});
let exportFormat='mp4';
const exportProfiles={mp4:{height:1080,fps:30,quality:'standard'},gif:{height:480,fps:15,quality:'standard'}};
function configureExportFormat(){
 const previous=exportProfiles[exportFormat];previous.height=Number($('#export-resolution').value);previous.fps=Number($('#export-fps').value);previous.quality=$('#export-quality').value;
 exportFormat=$('#export-format').value;const gif=exportFormat==='gif',profile=exportProfiles[exportFormat];
 $('#export-resolution').innerHTML=(gif?[[240,'240p · Small'],[360,'360p · Compact'],[480,'480p · Balanced'],[720,'720p · Large']]:[[720,'720p · HD'],[1080,'1080p · Full HD'],[2160,'2160p · 4K']]).map(([value,label])=>'<option value="'+value+'">'+label+'</option>').join('');
 $('#export-fps').innerHTML=(gif?[10,15,20,24,25,30]:[24,25,30,60]).map(value=>'<option value="'+value+'">'+value+' fps</option>').join('');
 $('#export-quality').innerHTML=gif?'<option value="standard">Standard · smaller file</option><option value="high">High · smoother color</option>':'<option value="standard">Standard · faster export</option><option value="high">High · finer detail</option>';
 $('#export-resolution').value=profile.height;$('#export-fps').value=profile.fps;$('#export-quality').value=profile.quality;
 $('#export-format-badge').textContent=gif?'GIF':'MP4';$('#export-loop-field').hidden=!gif;$('#export-action-label').textContent=gif?'Export GIF':'Export video';
 $('#export-message').textContent=gif?'Animated GIF with your video layers and text. GIF does not include audio.':'H.264 video with AAC audio. Choose where to save next.';
 $('#export-progress').hidden=true;$('#show-output').hidden=true;$('#start-export').hidden=false;$('#export-cancel').textContent='Cancel';
}
$('#export-format').onchange=configureExportFormat;
function exportDialog(){if(!project.clips.length)return;pause();$('#export-name').textContent=project.name;$('#export-summary').textContent=project.ratio+' · '+C.timecode(C.duration(project),project.fps);if(exportFormat==='mp4')$('#export-fps').value=project.fps;configureExportFormat();$('#start-export').disabled=false;$('#export-dialog').showModal();}
$('#export-button').onclick=exportDialog;
$('#export-form').onsubmit=async e=>{
 e.preventDefault();if(!api||exporting)return;const gif=$('#export-format').value==='gif';
 const options={format:$('#export-format').value,height:Number($('#export-resolution').value),fps:Number($('#export-fps').value),quality:$('#export-quality').value,loop:$('#export-loop').checked};
 exporting=true;$('#start-export').disabled=true;$$('#export-form select, #export-loop').forEach(el=>el.disabled=true);$('#export-progress').hidden=false;$('#export-progress-label').textContent=gif?'Rendering animation…':'Rendering video…';$('#export-percent').textContent='0%';$('#export-progress-bar').value=0;$('#export-message').textContent='Keep this window open while your '+(gif?'animation':'video')+' renders.';
 try{const r=await api.exportVideo(project,options);if(r.cancelled){$('#export-progress').hidden=true;$('#export-message').textContent='Choose where to save when you are ready.';}else{$('#export-progress-label').textContent=gif?'Your GIF is ready':'Your video is ready';$('#export-message').textContent='Saved to '+r.path;$('#show-output').hidden=false;$('#start-export').hidden=true;$('#export-cancel').textContent='Done';}}
 catch(e){$('#export-progress').hidden=true;$('#export-message').textContent=String(e.message).replace(/^Error invoking remote method '[^']+': Error: /,'');}
 finally{exporting=false;$('#start-export').disabled=false;$$('#export-form select, #export-loop').forEach(el=>el.disabled=false);}
};
$('#export-cancel').onclick=()=>{if(exporting){api.cancelExport();$('#export-message').textContent='Cancelling export…';}else $('#export-dialog').close();};
$('#export-dialog').addEventListener('cancel',e=>{if(exporting)e.preventDefault();});
$('#show-output').onclick=()=>api.showOutput();
api?.onProgress(p=>{$('#export-percent').textContent=Math.round(p)+'%';$('#export-progress-bar').value=p;});
$('#minimize').onclick=()=>api?.minimize();$('#maximize').onclick=()=>api?.maximize();$('#close-window').onclick=async()=>{if(await confirmDiscard()){dirty=false;api?.close();}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$('dialog[open]'))return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl){const actions={a:selectAllTimeline,c:copyTimeline,x:cutTimeline,v:pasteTimeline,g:e.shiftKey?ungroupTimeline:groupTimeline,i:importMedia,s:()=>saveProject(e.shiftKey),o:openProject,n:newProject,b:split,d:duplicateClip,z:e.shiftKey?redo:undo,y:redo};if(actions[e.key.toLowerCase()]){e.preventDefault();actions[e.key.toLowerCase()]();}}else if(e.code==='Space'){e.preventDefault();play();}else if(['Delete','Backspace'].includes(e.key)){e.preventDefault();(e.shiftKey?rippleDelete:deleteClip)();}else if(e.key.toLowerCase()==='k'){e.preventDefault();addKeyframe();}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();pause();seek(time+(e.key==='ArrowLeft'?-1:1)/project.fps);}else if(e.key==='Home'){e.preventDefault();pause();seek(0);}});
api?.onAction(async action=>{if(action==='close'&&await confirmDiscard()){dirty=false;api.close();}});
function previewBounds(c){if(!c||c.disabled||C.trackState(project,c).hidden||c.track==='audio'||time<c.start||time>=c.start+C.clipDuration(c))return null;const W=canvas.width,H=canvas.height,v=C.evaluated(c,time-c.start);let width,height;if(c.track==='text'){ctx.save();const size=c.fontSize*H/1080;ctx.font=(c.bold?'bold ':'')+size+'px '+(c.fontFamily||'Arial');width=Math.max(...c.text.split('\n').map(line=>ctx.measureText(line).width))+24*H/1080;height=c.text.split('\n').length*size*1.2+24*H/1080;ctx.restore();}else{const a=project.assets.find(a=>a.id===c.assetId);if(!a)return null;const fit=Math.min(W/a.width,H/a.height)*(c.scale||1),r=(c.rotation||0)*Math.PI/180;width=Math.abs(a.width*fit*Math.cos(r))+Math.abs(a.height*fit*Math.sin(r));height=Math.abs(a.width*fit*Math.sin(r))+Math.abs(a.height*fit*Math.cos(r));}return {x:W/2+v.x*W-width/2,y:H/2+v.y*H-height/2,width,height};}
function renderPreviewSelection(){const b=previewBounds(selection()),overlay=$('#preview-selection');overlay.hidden=!b||playing;if(b)Object.assign(overlay.style,{left:b.x/canvas.width*100+'%',top:b.y/canvas.height*100+'%',width:b.width/canvas.width*100+'%',height:b.height/canvas.height*100+'%'});}
let previewDrag=null;
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||playing)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height,contains=b=>b&&x>=b.x&&x<=b.x+b.width&&y>=b.y&&y<=b.y+b.height;let c=selection();if(!contains(previewBounds(c))){c=[...C.active(project,time,'video'),...C.active(project,time,'text')].reverse().find(c=>contains(previewBounds(c)));if(!c)return;setSelected(c.id);}if(C.trackState(project,c).locked){toast('This track is locked.');return;}const v=C.evaluated(c,time-c.start);previewDrag={id:c.id,x:e.clientX,y:e.clientY,initialX:v.x,initialY:v.y,width:r.width,height:r.height,before:snapshot(),moved:false};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!previewDrag)return;const c=project.clips.find(c=>c.id===previewDrag.id);if(!c)return;if(!previewDrag.moved){if(Math.hypot(e.clientX-previewDrag.x,e.clientY-previewDrag.y)<2)return;history.push(previewDrag.before);future=[];previewDrag.moved=true;}for(const [key,value]of [['x',C.clamp(previewDrag.initialX+(e.clientX-previewDrag.x)/previewDrag.width,-1,1)],['y',C.clamp(previewDrag.initialY+(e.clientY-previewDrag.y)/previewDrag.height,-1,1)]]){if(c.keyframes?.some(f=>key in f.values))C.setKeyframe(c,keyframeLocal(c),{[key]:value});else c[key]=value;}changed();draw();});
function finishPreviewDrag(){if(!previewDrag)return;previewDrag=null;renderInspector();renderTimeline();}
canvas.addEventListener('pointerup',finishPreviewDrag);canvas.addEventListener('pointercancel',finishPreviewDrag);
$('#timeline-scroll').addEventListener('scroll',()=>{$('.track-labels').style.transform='translateY(-'+$('#timeline-scroll').scrollTop+'px)';});
function keyframeLocal(c=selection()){return C.clamp(time-(c?.start||0),0,c?C.clipDuration(c):0);}
function keyframeValues(c){return Object.fromEntries((c.track==='audio'?['volume']:['x','y','opacity']).map(k=>[k,C.propertyAt(c,k,keyframeLocal(c))]));}
function addKeyframe(){const c=selection();if(!c)return;pause();remember();C.setKeyframe(c,keyframeLocal(c),keyframeValues(c));inspectorTab='motion';changed();renderInspector();renderTimeline();draw();}
function motionInspector(c){const local=keyframeLocal(c),keys=c.track==='audio'?['volume']:['x','y','opacity'];return '<div class="motion-intro"><span class="eyebrow">FRAME BY FRAME</span><h3>Shape the movement</h3><p>Move the playhead, set a keyframe, then change a value. Motion blends smoothly between your points.</p></div><div class="keyframe-actions"><button class="button accent" data-keyframe-add>◇ Set keyframe</button><button class="icon-button" data-keyframe-remove title="Remove keyframe at playhead" aria-label="Remove keyframe">−</button></div><div id="keyframe-status" class="inspector-hint"></div><div class="property-section">'+keys.map(k=>'<div class="range-label"><label for="motion-'+k+'">'+({x:'Horizontal',y:'Vertical',opacity:'Opacity',volume:'Volume'}[k])+'</label><output data-motion-value="'+k+'">'+Math.round(C.propertyAt(c,k,local)*100)+'%</output></div><input id="motion-'+k+'" type="range" data-motion-prop="'+k+'" min="'+(['x','y'].includes(k)?-1:0)+'" max="'+(k==='volume'?2:1)+'" step=".01" value="'+C.propertyAt(c,k,local)+'">').join('')+'</div><h3 class="keyframe-heading">Keyframes</h3><div class="keyframe-list">'+(c.keyframes?.length?c.keyframes.map((f,i)=>'<button data-keyframe-jump="'+i+'"><span>◇</span><strong>'+C.timecode(f.time,project.fps)+'</strong><small>'+Object.keys(f.values).join(' · ')+'</small></button>').join(''):'<p class="inspector-hint">No motion points yet. Add one here or choose a preset in Motion.</p>')+'</div>'+(c.keyframes?.length?'<button class="text-button" data-keyframe-clear>Clear all motion</button>':'');}
function renderKeyframeStatus(){const c=selection();if(!c||inspectorTab!=='motion')return;const local=keyframeLocal(c),at=c.keyframes?.find(f=>Math.abs(f.time-local)<1/project.fps/2);const label=$('#keyframe-status');if(label)label.textContent=C.timecode(local,project.fps)+' into clip · '+(at?'Keyframe here':'Between keyframes');$$('[data-motion-prop]').forEach(el=>{el.value=C.propertyAt(c,el.dataset.motionProp,local);const output=$('[data-motion-value="'+el.dataset.motionProp+'"]');if(output)output.textContent=Math.round(Number(el.value)*100)+'%';});}
$('#inspector-content').addEventListener('click',e=>{const c=selection();if(!c)return;if(e.target.closest('[data-keyframe-add]'))addKeyframe();if(e.target.closest('[data-keyframe-remove]')){const local=keyframeLocal(c);if(!c.keyframes?.some(f=>Math.abs(f.time-local)<1/project.fps/2))return;remember();c.keyframes=c.keyframes.filter(f=>Math.abs(f.time-local)>=1/project.fps/2);changed();renderInspector();renderTimeline();draw();}if(e.target.closest('[data-keyframe-clear]')){remember();Object.assign(c,keyframeValues(c));c.keyframes=[];changed();renderInspector();renderTimeline();draw();}const jump=e.target.closest('[data-keyframe-jump]');if(jump){pause();seek(c.start+c.keyframes[Number(jump.dataset.keyframeJump)].time);}});
let editingMotion=null;
$('#inspector-content').addEventListener('pointerdown',e=>{if(e.target.dataset.motionProp){remember();editingMotion=e.target.dataset.motionProp;pause();}});
$('#inspector-content').addEventListener('focusin',e=>{if(e.target.dataset.motionProp&&editingMotion!==e.target.dataset.motionProp){remember();editingMotion=e.target.dataset.motionProp;}});
$('#inspector-content').addEventListener('focusout',()=>editingMotion=null);
$('#inspector-content').addEventListener('change',e=>{if(e.target.dataset.motionProp){renderInspector();renderKeyframeStatus();}});
$('#inspector-content').addEventListener('input',e=>{const key=e.target.dataset.motionProp,c=selection();if(!key||!c)return;const local=keyframeLocal(c),val=Number(e.target.value);if(!c.keyframes?.some(f=>key in f.values))C.setKeyframe(c,0,{[key]:c[key]??(key==='opacity'||key==='volume'?1:0)});C.setKeyframe(c,local,{[key]:val});changed();renderTimeline();renderKeyframeStatus();syncMedia();draw();});
$('#library-content').addEventListener('click',e=>{const motion=e.target.closest('[data-motion]'),transition=e.target.closest('[data-transition-preset]'),style=e.target.closest('[data-title-style]');if(motion){const c=selection();if(!c||c.track==='audio'){toast('Select a video or title clip first.');return;}remember();C.motionPreset(c,motion.dataset.motion);inspectorTab='motion';changed();renderInspector();renderTimeline();seek(c.start);toast('Motion applied. Edit its keyframes in Inspector.');}if(transition){const c=selection();if(c?.track!=='video'){toast('Select the second video clip first.');return;}const before=snapshot();try{C.applyDissolve(project,c.id,1,transition.dataset.transitionPreset);history.push(before);future=[];inspectorTab='video';changed();renderAll();seek(c.start);}catch(e){toast(e.message);}}if(style){addText(style.dataset.titleStyle);}});
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const reg=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
reg({name:'get_editing_project',description:'Read the current project, clips, and playhead without changing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return {name:project.name,ratio:project.ratio,duration:C.duration(project),playhead:time,clips:project.clips,assets:project.assets.map(a=>({id:a.id,name:a.name,type:a.type,duration:a.duration}))};}});
reg({name:'add_text_overlay',description:'Create a text clip at a specified timeline time.',inputSchema:{type:'object',properties:{text:{type:'string'},start:{type:'number',minimum:0},duration:{type:'number',minimum:.1}},required:['text','start','duration'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(typeof input.text!=='string'||input.text.length>2000||!Number.isFinite(input.start)||input.start<0||!Number.isFinite(input.duration)||input.duration<.1)throw Error('Invalid text clip.');remember();const c=C.createText(input.start);c.text=input.text;c.out=input.duration;project.clips.push(c);selected=c.id;changed();renderAll();seek(input.start);return {id:c.id,start:c.start,duration:input.duration};}});
}
renderAll();
